font:
  normal:
    family: Dina
    style: Medium
  bold:
    family: Dina
    style: Bold
  italic:
    family: Dina
    style: MediumItalic
  bold_italic:
    family: Dina
    style: BoldItalic
  size: 12.0
  offset:
    x: 1
    y: 0
  glyph_offset:
    x: 0
    y: 0
  use_thin_strokes: true
  builtin_box_drawing: true
