user_pref("font.name.monospace.x-western", "Iosevka Nerd Font");
user_pref("font.name.sans-serif.x-western", "Iosevka Nerd Font");
user_pref("font.name.serif.x-western", "Iosevka Nerd Font");
//----------------------------------------
user_pref("floorp.lepton.interface", 3);
user_pref("floorp.hide.unifiedExtensionsButtton", false);
user_pref("floorp.browser.note.memos.using", 0);
user_pref("floorp.browser.sidebar.enable", false);
user_pref("floorp.browser.sidebar.is.displayed", false);
user_pref("floorp.browser.sidebar2.global.webpanel.width", 341);
user_pref("floorp.browser.workspaces.disabledBySystem", false);
user_pref("floorp.download.notification", 2);
user_pref("floorp.Tree-type.verticaltab.optimization", true);
user_pref("floorp.bookmarks.fakestatus.mode", false);
user_pref("floorp.browser.workspace.all", "Default");
user_pref("floorp.browser.workspaces.enabled", false);
//--------------------------------------
user_pref("userChrome.autohide.back_button", true);
user_pref("userChrome.autohide.forward_button", true);
user_pref("userChrome.autohide.navbar", true);
user_pref("userChrome.autohide.page_action", true);
user_pref("userChrome.autohide.sidebar", false);
user_pref("userChrome.autohide.tab", false);
user_pref("userChrome.centered.bookmarkbar", true);
user_pref("userChrome.centered.tab", true);
user_pref("userChrome.centered.urlbar", true);
user_pref("userChrome.hidden.bookmarkbar_icon", false);
user_pref("userChrome.hidden.bookmarkbar_label", false);
user_pref("userChrome.hidden.navbar", false);
user_pref("userChrome.hidden.sidebar_header", false);
user_pref("userChrome.hidden.tab_icon", false);
user_pref("userChrome.hidden.tabbar", false);
user_pref("userChrome.hidden.urlbar_iconbox", true);
user_pref("userChrome.icon.disabled", false);
user_pref("userChrome.sidebar.overlap", false);
user_pref("userChrome.tab.bottom_rounded_corner", false);
user_pref("userChrome.tab.color_like_toolbar", false);
user_pref("userChrome.tab.connect_to_window", false);
user_pref("userChrome.tab.lepton_like_padding", false);
user_pref("userChrome.tab.newtab_button_like_tab", false);
user_pref("userChrome.tab.newtab_button_proton", true);
user_pref("userChrome.tabbar.as_titlebar", false);
user_pref("userChrome.tabbar.one_liner", false);
user_pref("userChrome.urlView.go_button_when_typing", false);
user_pref("userChrome.urlView.move_icon_to_left", false);
//-----------------------------------
user_pref("browser.aboutwelcome.enabled", false);
user_pref("browser.display.use_system_colors", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.tabs.firefox-view", false);
user_pref("browser.tabs.inTitlebar", 0);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.toolbars.bookmarks.visibility", "never");
user_pref("browser.uidensity", 1);
