[colors.bright]
black = "0x3c3836"
blue = "#05f948"
cyan = "#05f948"
green = "#05f948"
magenta = "#05f948"
red = "#05f948"
white = "#05f948"
yellow = "#05f948"

[colors.normal]
black = "#000000"
blue = "#05f948"
cyan = "#05f948"
green = "#05f948"
magenta = "#05f948"
red = "#05f948"
white = "#05f948"
yellow = "#05f948"

[colors.primary]
background = "0x282828"
foreground = "0xd4be98"

[cursor.style]
shape = "underline"

[cursor.vi_mode_style]
shape = "underline"

[font]
size = 11

[font.normal]
family = "SpaceMonoNerdFont"

[window]
dynamic_padding = true
opacity = 0.8

[window.padding]
x = 10
y = 5
